### ISSUE TITLE
MMM-ISS-Live   new live movie

### ISSUE THREAD

**Issue by Manu85340** [KristjanESPERANTO/MMM-ISS-Live#1]
@KristjanESPERANTO hello, I just saw a live video from the ISS on YouTube which is really very pretty and very complete with small windows which show the position on a planisphere, the cities over which it passes etc. do you think it would be possible to put this new view in place of the old one?
I'll give you the address of the YouTube link:

https://www.youtube.com/watch?v=xRPjKQtRXR8

Thanks again for everything you do

**Comment by KristjanESPERANTO** [comment]
Hi @Manu85340 :slightly_smiling_face:  Nice idea, thanks!

As I found a third video stream, I have now added an option to the module to select a stream.

Update your module and have a look at the README to see how you can change the stream. Please give me feedback if this works well for you.

**Comment by 85340olonne** [comment]
great, thank you for your quick response and your responsiveness, I will try this after eating

**Comment by Manu85340** [comment]
you are the best ! it works without problem
thank you for your work

**Comment by KristjanESPERANTO** [comment]
I'm glad to hear that! :slightly_smiling_face: 

Please [give the modules you like a star](https://docs.github.com/en/get-started/exploring-projects-on-github/saving-repositories-with-stars#starring-a-repository), that's a small but nice sign of appreciation for developers. The stars are now also displayed in [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I'm working on.
