### ISSUE TITLE
ISS Tracker

### ISSUE THREAD

**Issue by Manu85340** [KristjanESPERANTO/MMM-ISS-Live#2]
Hello Kristjan, I still need your help...
to improve the monitoring of the ISS I need your expertise, in the sites that you added to the module (that of afartv) I would like to take this opportunity to thank you again for your work, the page is well done but the windows at the bottom left are very small and it is complicated to follow your passage precisely, do you think it would be possible to enlarge them, I tried but I don't see how! or otherwise I thought of another solution which would consist of using the original module of your MMM-ISS-Live and adding another module which would allow geographical tracking, I saw this site and zoomed in on the map it would be perfect...
https://isstracker.pl/en
I took a screenshot and it would be awesome to have this view, maybe I'm dreaming but it would be so beautiful

![image](https://github.com/KristjanESPERANTO/MMM-ISS-Live/assets/28225963/227d5b55-291f-4b85-8718-ed05310a3d22)

**Comment by KristjanESPERANTO** [comment]
I think it could be possible to enlarge the part from the video, but I'm currently investing my time in other projects.

Using data from isstracker.pl might also be possible. Maybe ask in the forum (https://forum.magicmirror.builders/category/9/requests) if anyone is interested in building something like this.

Third option: You try to build it yourself :slightly_smiling_face:  I don't know your level of knowledge on this topic, but it's a great thing to deal with JavaScript and realise ideas with it :smiley: Many of the MagicMirror modules were created by non-programmers.

**Comment by 85340olonne** [comment]
Thank you for your response, I don't have the skills to create a module, I've never tried, are there any forums that explain how to do it? I'm ready to try, if it's too complicated for me then I'll take your option number 3 😉

**Comment by KristjanESPERANTO** [comment]
In the docs of MM is a section about module development: https://docs.magicmirror.builders/development/introduction.html#general-advice

If you don't have any experience with JavaScript there are a lot of free tutorials, like this one: https://www.w3schools.com/js/DEFAULT.asp

It takes a little patience, but it's worth it :smiley:

**Comment by Manu85340** [comment]
good evening Kristjan, could you add this youtube stream? this will solve the tracking problem on the map, that would be really cool of you, thanks again
https://www.youtube.com/watch?v=SjfvShvQsIo

**Comment by Manu85340** [comment]
Sorry Kristjan, but this is not the right link, this one is cut every day and contains advertising, sorry

**Comment by KristjanESPERANTO** [comment]
It's a pity that the link is unsuitable. The layout looks very good.

That would be the link you have to add to the config: <https://www.youtube.com/embed/SjfvShvQsIo?si=6GNMcHGm0Ra2I8PJ>

**Comment by Manu85340** [comment]
Thank you for your response, unfortunately these links are only functional for 24 hours, it's a shame because it really is the ideal module to follow the progress of the ISS (GPS map, planisphère and live view of the earth) :-(

**Comment by Manu85340** [comment]
hello Kristjan, can you explain something to me please? when I sent you the youtube link:

https://www.youtube.com/watch?v=SjfvShvQsIo

you sent me another link to make it work:

  https://www.youtube.com/embed/SjfvShvQsIo?si=6GNMcHGm0Ra2I8PJ

How did you find this link? I would like to understand so that I can put different links on your ISS module and each time I paste a link nothing works.
thank you for your help

**Comment by KristjanESPERANTO** [comment]
Here is an explaination about that: https://total.wpexplorer.com/docs/get-embed-urllink-youtube-video/ :slightly_smiling_face:

**Comment by Manu85340** [comment]
too strong !!! thank's     ;-)

**Comment by Manu85340** [comment]
Hi Kristjan, @mumblebaj has been working on the rugby module for a few weeks, he has already done a lot of work, and I saw that I had updated the module:
  https://github.com/0m4r/MMM-SoccerLiveScore
I asked @mumblebaj if he could do something like you for the presentation of the league choice tables etc. he told me that for him it seemed complicated but that if you could it would be with great pleasure, his module is as follows:
https://github.com/mumblebaj/MMM-Rugby.git
I don't know if it's possible for you but it would be something great, a lot of people would like to have this module on their MM
Thanks again for updating the weather module
  MMM-OneCallWeather
