### ISSUE TITLE
How to update ISS live video

### ISSUE THREAD

**Issue by Buzzlig** [KristjanESPERANTO/MMM-ISS-Live#3]
Hello Kristijan,

How do I go about updating the MMM-ISS-Live module?

Regards.

**Comment by KristjanESPERANTO** [comment]
Hi @Buzzlig, I just added a section for updating to the README file: https://github.com/KristjanESPERANTO/MMM-ISS-Live?tab=readme-ov-file#update 🙂

**Comment by Buzzlig** [comment]
Kristjan good morning,

Thank you for your help, the update worked 😃.

Regards.


________________________________
